---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nodeflux/nodefluxautomacao.com.br
    - /bin/cp -rf * $DEPLOYPATH/
    - /bin/cp -rf dist/* $DEPLOYPATH/
    - /bin/cp -f .htaccess $DEPLOYPATH/.htaccess
